//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHmiClientSample
{
	public sealed partial class IoDevice : PHmiClient.Tags.IoDeviceBase
	{
		public IoDevice() : base(1, "IoDevice")
		{
			M0 = AddDigitalTag(1, "M0", () => PHmiResources.m0);
			M1 = AddDigitalTag(2, "M1", () => PHmiResources.m1);
			M2 = AddDigitalTag(3, "M2", () => PHmiResources.m2);
			M3 = AddDigitalTag(4, "M3", () => PHmiResources.m3);
			D0 = AddNumericTag(1, "D0", () => PHmiResources.d0, () => PHmiResources.n0_00, () => PHmiResources.a, 0, 100);
		}
		
		public PHmiClient.Tags.IDigitalTag M0 { get; private set; }
		
		public PHmiClient.Tags.IDigitalTag M1 { get; private set; }
		
		public PHmiClient.Tags.IDigitalTag M2 { get; private set; }
		
		public PHmiClient.Tags.IDigitalTag M3 { get; private set; }
		
		public PHmiClient.Tags.INumericTag D0 { get; private set; }
	}
	
	public sealed partial class Alarms : PHmiClient.Alarms.AlarmCategoryBase
	{
		public Alarms() : base(1, "Alarms", () => PHmiResources.alarms)
		{
			AddAlarmInfo(1, () => PHmiResources.m0, () => PHmiResources.alarm);
			AddAlarmInfo(2, () => PHmiResources.m1, () => PHmiResources.alarm);
			AddAlarmInfo(3, () => PHmiResources.m2, () => PHmiResources.m2_alarm);
		}
	}
	
	public sealed partial class Trends : PHmiClient.Trends.TrendsCategoryBase
	{
		public Trends() : base(1, "Trends", 50000000)
		{
			Trend = AddTrendTag(1, "Trend", () => PHmiResources.trend, () => PHmiResources.n0_00, () => PHmiResources.a, 0, 100);
		}
		
		public PHmiClient.Trends.ITrendTag Trend { get; private set; }
	}
	
	public sealed partial class PHmi : PHmiClient.PHmiSystem.PHmiBase
	{
		public PHmi() : base("localhost:4891", "a249ca57-c994-457a-aba1-cde4de471aff")
		{
			IoDevice = AddIoDevice(new IoDevice());
			Alarms = AddAlarmCategory(new Alarms());
			Trends = AddTrendsCategory(new Trends());
			Log = AddLog(1, "Log");
		}
		
		public IoDevice IoDevice { get; private set; }
		
		public Alarms Alarms { get; private set; }
		
		public Trends Trends { get; private set; }
		
		public PHmiClient.Logs.LogAbstract Log { get; private set; }
	}
}
