//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets53BCFF5AEFA65AF81D9FE8252E11AC15609F39C17781E8EE778CA62AAB9D9D1B))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets53BCFF5AEFA65AF81D9FE8252E11AC15609F39C17781E8EE778CA62AAB9D9D1B : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets53BCFF5AEFA65AF81D9FE8252E11AC15609F39C17781E8EE778CA62AAB9D9D1B()
        {
            this.EdmEntityContainerName = "PHmiModelContext";
            this.StoreEntityContainerName = "PHmiModelStoreContainer";
            this.HashOverMappingClosure = "d1e09ac61c7058a615b2e1d08b992b6cd5d54a85035ce7e2b47e69fd9f4e134a";
            this.HashOverAllExtentViews = "78363abd74685fc7c069055ba6bb99526e9c2e9b37ee44173c7c768e0e18cc68";
            this.ViewCount = 22;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.alarm_categories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.alarm_categories", @"
    SELECT VALUE -- Constructing alarm_categories
        [PHmiModel.Store.alarm_categories](T1.[alarm_categories.id], T1.[alarm_categories.name], T1.[alarm_categories.description], T1.[alarm_categories.time_to_store])
    FROM (
        SELECT 
            T.id AS [alarm_categories.id], 
            T.name AS [alarm_categories.name], 
            T.description AS [alarm_categories.description], 
            T.time_to_store AS [alarm_categories.time_to_store], 
            True AS _from0
        FROM PHmiModelContext.alarm_categories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.alarm_tags
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.alarm_tags", @"
    SELECT VALUE -- Constructing alarm_tags
        [PHmiModel.Store.alarm_tags](T1.[alarm_tags.id], T1.[alarm_tags.name], T1.[alarm_tags.ref_dig_tags], T1.[alarm_tags.location], T1.[alarm_tags.description], T1.[alarm_tags.privilege], T1.[alarm_tags.ref_categories], T1.[alarm_tags.acknowledgeable])
    FROM (
        SELECT 
            T.id AS [alarm_tags.id], 
            T.name AS [alarm_tags.name], 
            T.ref_dig_tags AS [alarm_tags.ref_dig_tags], 
            T.location AS [alarm_tags.location], 
            T.description AS [alarm_tags.description], 
            T.privilege AS [alarm_tags.privilege], 
            T.ref_categories AS [alarm_tags.ref_categories], 
            T.acknowledgeable AS [alarm_tags.acknowledgeable], 
            True AS _from0
        FROM PHmiModelContext.alarm_tags AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.dig_tags
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.dig_tags", @"
    SELECT VALUE -- Constructing dig_tags
        [PHmiModel.Store.dig_tags](T1.[dig_tags.id], T1.[dig_tags.name], T1.[dig_tags.ref_io_devices], T1.[dig_tags.device], T1.[dig_tags.description], T1.[dig_tags.can_read])
    FROM (
        SELECT 
            T.id AS [dig_tags.id], 
            T.name AS [dig_tags.name], 
            T.ref_io_devices AS [dig_tags.ref_io_devices], 
            T.device AS [dig_tags.device], 
            T.description AS [dig_tags.description], 
            T.can_read AS [dig_tags.can_read], 
            True AS _from0
        FROM PHmiModelContext.dig_tags AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.io_devices
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.io_devices", @"
    SELECT VALUE -- Constructing io_devices
        [PHmiModel.Store.io_devices](T1.[io_devices.id], T1.[io_devices.name], T1.[io_devices.type], T1.[io_devices.options])
    FROM (
        SELECT 
            T.id AS [io_devices.id], 
            T.name AS [io_devices.name], 
            T.type AS [io_devices.type], 
            T.options AS [io_devices.options], 
            True AS _from0
        FROM PHmiModelContext.io_devices AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.num_tag_types
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.num_tag_types", @"
    SELECT VALUE -- Constructing num_tag_types
        [PHmiModel.Store.num_tag_types](T1.[num_tag_types.id], T1.[num_tag_types.name])
    FROM (
        SELECT 
            T.id AS [num_tag_types.id], 
            T.name AS [num_tag_types.name], 
            True AS _from0
        FROM PHmiModelContext.num_tag_types AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.num_tags
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.num_tags", @"
    SELECT VALUE -- Constructing num_tags
        [PHmiModel.Store.num_tags](T1.[num_tags.id], T1.[num_tags.name], T1.[num_tags.ref_io_devices], T1.[num_tags.ref_tag_types], T1.[num_tags.device], T1.[num_tags.description], T1.[num_tags.can_read], T1.[num_tags.eng_unit], T1.[num_tags.raw_min], T1.[num_tags.raw_max], T1.[num_tags.eng_min], T1.[num_tags.eng_max], T1.[num_tags.format])
    FROM (
        SELECT 
            T.id AS [num_tags.id], 
            T.name AS [num_tags.name], 
            T.ref_io_devices AS [num_tags.ref_io_devices], 
            T.ref_tag_types AS [num_tags.ref_tag_types], 
            T.device AS [num_tags.device], 
            T.description AS [num_tags.description], 
            T.can_read AS [num_tags.can_read], 
            T.eng_unit AS [num_tags.eng_unit], 
            T.raw_min AS [num_tags.raw_min], 
            T.raw_max AS [num_tags.raw_max], 
            T.eng_min AS [num_tags.eng_min], 
            T.eng_max AS [num_tags.eng_max], 
            T.format AS [num_tags.format], 
            True AS _from0
        FROM PHmiModelContext.num_tags AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.trend_categories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.trend_categories", @"
    SELECT VALUE -- Constructing trend_categories
        [PHmiModel.Store.trend_categories](T1.[trend_categories.id], T1.[trend_categories.name], T1.[trend_categories.time_to_store], T1.[trend_categories.period])
    FROM (
        SELECT 
            T.id AS [trend_categories.id], 
            T.name AS [trend_categories.name], 
            T.time_to_store AS [trend_categories.time_to_store], 
            T.period AS [trend_categories.period], 
            True AS _from0
        FROM PHmiModelContext.trend_categories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.trend_tags
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.trend_tags", @"
    SELECT VALUE -- Constructing trend_tags
        [PHmiModel.Store.trend_tags](T1.[trend_tags.id], T1.[trend_tags.name], T1.[trend_tags.ref_num_tags], T1.[trend_tags.description], T1.[trend_tags.ref_categories], T1.[trend_tags.ref_triggers])
    FROM (
        SELECT 
            T.id AS [trend_tags.id], 
            T.name AS [trend_tags.name], 
            T.ref_num_tags AS [trend_tags.ref_num_tags], 
            T.description AS [trend_tags.description], 
            T.ref_categories AS [trend_tags.ref_categories], 
            T.ref_triggers AS [trend_tags.ref_triggers], 
            True AS _from0
        FROM PHmiModelContext.trend_tags AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.alarm_categories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.alarm_categories", @"
    SELECT VALUE -- Constructing alarm_categories
        [PHmiModel.alarm_categories](T1.[alarm_categories.id], T1.[alarm_categories.name], T1.[alarm_categories.description], T1.[alarm_categories.time_to_store])
    FROM (
        SELECT 
            T.id AS [alarm_categories.id], 
            T.name AS [alarm_categories.name], 
            T.description AS [alarm_categories.description], 
            T.time_to_store AS [alarm_categories.time_to_store], 
            True AS _from0
        FROM PHmiModelStoreContainer.alarm_categories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.alarm_tags
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.alarm_tags", @"
    SELECT VALUE -- Constructing alarm_tags
        [PHmiModel.alarm_tags](T1.[alarm_tags.id], T1.[alarm_tags.name], T1.[alarm_tags.ref_dig_tags], T1.[alarm_tags.location], T1.[alarm_tags.description], T1.[alarm_tags.privilege], T1.[alarm_tags.ref_categories], T1.[alarm_tags.acknowledgeable])
    FROM (
        SELECT 
            T.id AS [alarm_tags.id], 
            T.name AS [alarm_tags.name], 
            T.ref_dig_tags AS [alarm_tags.ref_dig_tags], 
            T.location AS [alarm_tags.location], 
            T.description AS [alarm_tags.description], 
            T.privilege AS [alarm_tags.privilege], 
            T.ref_categories AS [alarm_tags.ref_categories], 
            T.acknowledgeable AS [alarm_tags.acknowledgeable], 
            True AS _from0
        FROM PHmiModelStoreContainer.alarm_tags AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.dig_tags
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.dig_tags", @"
    SELECT VALUE -- Constructing dig_tags
        [PHmiModel.dig_tags](T1.[dig_tags.id], T1.[dig_tags.name], T1.[dig_tags.ref_io_devices], T1.[dig_tags.device], T1.[dig_tags.description], T1.[dig_tags.can_read])
    FROM (
        SELECT 
            T.id AS [dig_tags.id], 
            T.name AS [dig_tags.name], 
            T.ref_io_devices AS [dig_tags.ref_io_devices], 
            T.device AS [dig_tags.device], 
            T.description AS [dig_tags.description], 
            T.can_read AS [dig_tags.can_read], 
            True AS _from0
        FROM PHmiModelStoreContainer.dig_tags AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.io_devices
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.io_devices", @"
    SELECT VALUE -- Constructing io_devices
        [PHmiModel.io_devices](T1.[io_devices.id], T1.[io_devices.name], T1.[io_devices.type], T1.[io_devices.options])
    FROM (
        SELECT 
            T.id AS [io_devices.id], 
            T.name AS [io_devices.name], 
            T.type AS [io_devices.type], 
            T.options AS [io_devices.options], 
            True AS _from0
        FROM PHmiModelStoreContainer.io_devices AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.num_tag_types
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.num_tag_types", @"
    SELECT VALUE -- Constructing num_tag_types
        [PHmiModel.num_tag_types](T1.[num_tag_types.id], T1.[num_tag_types.name])
    FROM (
        SELECT 
            T.id AS [num_tag_types.id], 
            T.name AS [num_tag_types.name], 
            True AS _from0
        FROM PHmiModelStoreContainer.num_tag_types AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.num_tags
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.num_tags", @"
    SELECT VALUE -- Constructing num_tags
        [PHmiModel.num_tags](T1.[num_tags.id], T1.[num_tags.name], T1.[num_tags.ref_io_devices], T1.[num_tags.ref_tag_types], T1.[num_tags.device], T1.[num_tags.description], T1.[num_tags.can_read], T1.[num_tags.eng_unit], T1.[num_tags.raw_min], T1.[num_tags.raw_max], T1.[num_tags.eng_min], T1.[num_tags.eng_max], T1.[num_tags.format])
    FROM (
        SELECT 
            T.id AS [num_tags.id], 
            T.name AS [num_tags.name], 
            T.ref_io_devices AS [num_tags.ref_io_devices], 
            T.ref_tag_types AS [num_tags.ref_tag_types], 
            T.device AS [num_tags.device], 
            T.description AS [num_tags.description], 
            T.can_read AS [num_tags.can_read], 
            T.eng_unit AS [num_tags.eng_unit], 
            T.raw_min AS [num_tags.raw_min], 
            T.raw_max AS [num_tags.raw_max], 
            T.eng_min AS [num_tags.eng_min], 
            T.eng_max AS [num_tags.eng_max], 
            T.format AS [num_tags.format], 
            True AS _from0
        FROM PHmiModelStoreContainer.num_tags AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.trend_categories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.trend_categories", @"
    SELECT VALUE -- Constructing trend_categories
        [PHmiModel.trend_categories](T1.[trend_categories.id], T1.[trend_categories.name], T1.[trend_categories.time_to_store], T1.[trend_categories.period])
    FROM (
        SELECT 
            T.id AS [trend_categories.id], 
            T.name AS [trend_categories.name], 
            T.time_to_store AS [trend_categories.time_to_store], 
            T.period AS [trend_categories.period], 
            True AS _from0
        FROM PHmiModelStoreContainer.trend_categories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.trend_tags
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.trend_tags", @"
    SELECT VALUE -- Constructing trend_tags
        [PHmiModel.trend_tags](T1.[trend_tags.id], T1.[trend_tags.name], T1.[trend_tags.ref_num_tags], T1.[trend_tags.description], T1.[trend_tags.ref_categories], T1.[trend_tags.ref_triggers])
    FROM (
        SELECT 
            T.id AS [trend_tags.id], 
            T.name AS [trend_tags.name], 
            T.ref_num_tags AS [trend_tags.ref_num_tags], 
            T.description AS [trend_tags.description], 
            T.ref_categories AS [trend_tags.ref_categories], 
            T.ref_triggers AS [trend_tags.ref_triggers], 
            True AS _from0
        FROM PHmiModelStoreContainer.trend_tags AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.logs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.logs", @"
    SELECT VALUE -- Constructing logs
        [PHmiModel.Store.logs](T1.logs_id, T1.logs_name, T1.[logs.time_to_store])
    FROM (
        SELECT 
            T.id AS logs_id, 
            T.name AS logs_name, 
            T.time_to_store AS [logs.time_to_store], 
            True AS _from0
        FROM PHmiModelContext.logs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.logs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.logs", @"
    SELECT VALUE -- Constructing logs
        [PHmiModel.logs](T1.logs_id, T1.logs_name, T1.[logs.time_to_store])
    FROM (
        SELECT 
            T.id AS logs_id, 
            T.name AS logs_name, 
            T.time_to_store AS [logs.time_to_store], 
            True AS _from0
        FROM PHmiModelStoreContainer.logs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.settings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.settings", @"
    SELECT VALUE -- Constructing settings
        [PHmiModel.Store.settings](T1.settings_id, T1.settings_server, T1.[settings.stand_by_server], T1.settings_guid, T1.settings_guid2, T1.[settings.phmi_guid])
    FROM (
        SELECT 
            T.id AS settings_id, 
            T.server AS settings_server, 
            T.stand_by_server AS [settings.stand_by_server], 
            T.guid AS settings_guid, 
            T.guid2 AS settings_guid2, 
            T.phmi_guid AS [settings.phmi_guid], 
            True AS _from0
        FROM PHmiModelContext.settings AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.settings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.settings", @"
    SELECT VALUE -- Constructing settings
        [PHmiModel.settings](T1.settings_id, T1.settings_server, T1.[settings.stand_by_server], T1.settings_guid, T1.settings_guid2, T1.[settings.phmi_guid])
    FROM (
        SELECT 
            T.id AS settings_id, 
            T.server AS settings_server, 
            T.stand_by_server AS [settings.stand_by_server], 
            T.guid AS settings_guid, 
            T.guid2 AS settings_guid2, 
            T.phmi_guid AS [settings.phmi_guid], 
            True AS _from0
        FROM PHmiModelStoreContainer.settings AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelStoreContainer.users
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelStoreContainer.users", @"
    SELECT VALUE -- Constructing users
        [PHmiModel.Store.users](T1.users_id, T1.users_name, T1.users_description, T1.users_photo, T1.users_password, T1.users_enabled, T1.[users.can_change], T1.users_privilege)
    FROM (
        SELECT 
            T.id AS users_id, 
            T.name AS users_name, 
            T.description AS users_description, 
            T.photo AS users_photo, 
            T.password AS users_password, 
            T.enabled AS users_enabled, 
            T.can_change AS [users.can_change], 
            T.privilege AS users_privilege, 
            True AS _from0
        FROM PHmiModelContext.users AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for PHmiModelContext.users
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("PHmiModelContext.users", @"
    SELECT VALUE -- Constructing users
        [PHmiModel.users](T1.users_id, T1.users_name, T1.users_description, T1.users_photo, T1.users_password, T1.users_enabled, T1.[users.can_change], T1.users_privilege)
    FROM (
        SELECT 
            T.id AS users_id, 
            T.name AS users_name, 
            T.description AS users_description, 
            T.photo AS users_photo, 
            T.password AS users_password, 
            T.enabled AS users_enabled, 
            T.can_change AS [users.can_change], 
            T.privilege AS users_privilege, 
            True AS _from0
        FROM PHmiModelStoreContainer.users AS T
    ) AS T1");
        }
    }
}
