//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PHmiModel", "fk_alarm_ta_reference_alarm_ca", "alarm_categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PHmiModel.alarm_categories), "alarm_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PHmiModel.alarm_tags), true)]
[assembly: EdmRelationshipAttribute("PHmiModel", "fk_alarm_ta_reference_dig_tags", "dig_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PHmiModel.dig_tags), "alarm_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PHmiModel.alarm_tags), true)]
[assembly: EdmRelationshipAttribute("PHmiModel", "fk_dig_tags_reference_io_devic", "io_devices", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PHmiModel.io_devices), "dig_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PHmiModel.dig_tags), true)]
[assembly: EdmRelationshipAttribute("PHmiModel", "fk_trend_ta_reference_dig_tags", "dig_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PHmiModel.dig_tags), "trend_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PHmiModel.trend_tags), true)]
[assembly: EdmRelationshipAttribute("PHmiModel", "fk_num_tags_reference_io_devic", "io_devices", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PHmiModel.io_devices), "num_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PHmiModel.num_tags), true)]
[assembly: EdmRelationshipAttribute("PHmiModel", "fk_num_tags_reference_num_tag_", "num_tag_types", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PHmiModel.num_tag_types), "num_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PHmiModel.num_tags), true)]
[assembly: EdmRelationshipAttribute("PHmiModel", "fk_trend_ta_reference_num_tags", "num_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PHmiModel.num_tags), "trend_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PHmiModel.trend_tags), true)]
[assembly: EdmRelationshipAttribute("PHmiModel", "fk_trend_ta_reference_trend_ca", "trend_categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PHmiModel.trend_categories), "trend_tags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PHmiModel.trend_tags), true)]

#endregion

namespace PHmiModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PHmiModelContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PHmiModelContext object using the connection string found in the 'PHmiModelContext' section of the application configuration file.
        /// </summary>
        public PHmiModelContext() : base("name=PHmiModelContext", "PHmiModelContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PHmiModelContext object.
        /// </summary>
        public PHmiModelContext(string connectionString) : base(connectionString, "PHmiModelContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PHmiModelContext object.
        /// </summary>
        public PHmiModelContext(EntityConnection connection) : base(connection, "PHmiModelContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<alarm_categories> alarm_categories
        {
            get
            {
                if ((_alarm_categories == null))
                {
                    _alarm_categories = base.CreateObjectSet<alarm_categories>("alarm_categories");
                }
                return _alarm_categories;
            }
        }
        private ObjectSet<alarm_categories> _alarm_categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<alarm_tags> alarm_tags
        {
            get
            {
                if ((_alarm_tags == null))
                {
                    _alarm_tags = base.CreateObjectSet<alarm_tags>("alarm_tags");
                }
                return _alarm_tags;
            }
        }
        private ObjectSet<alarm_tags> _alarm_tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dig_tags> dig_tags
        {
            get
            {
                if ((_dig_tags == null))
                {
                    _dig_tags = base.CreateObjectSet<dig_tags>("dig_tags");
                }
                return _dig_tags;
            }
        }
        private ObjectSet<dig_tags> _dig_tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<io_devices> io_devices
        {
            get
            {
                if ((_io_devices == null))
                {
                    _io_devices = base.CreateObjectSet<io_devices>("io_devices");
                }
                return _io_devices;
            }
        }
        private ObjectSet<io_devices> _io_devices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<logs> logs
        {
            get
            {
                if ((_logs == null))
                {
                    _logs = base.CreateObjectSet<logs>("logs");
                }
                return _logs;
            }
        }
        private ObjectSet<logs> _logs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<num_tag_types> num_tag_types
        {
            get
            {
                if ((_num_tag_types == null))
                {
                    _num_tag_types = base.CreateObjectSet<num_tag_types>("num_tag_types");
                }
                return _num_tag_types;
            }
        }
        private ObjectSet<num_tag_types> _num_tag_types;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<num_tags> num_tags
        {
            get
            {
                if ((_num_tags == null))
                {
                    _num_tags = base.CreateObjectSet<num_tags>("num_tags");
                }
                return _num_tags;
            }
        }
        private ObjectSet<num_tags> _num_tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<settings> settings
        {
            get
            {
                if ((_settings == null))
                {
                    _settings = base.CreateObjectSet<settings>("settings");
                }
                return _settings;
            }
        }
        private ObjectSet<settings> _settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<trend_categories> trend_categories
        {
            get
            {
                if ((_trend_categories == null))
                {
                    _trend_categories = base.CreateObjectSet<trend_categories>("trend_categories");
                }
                return _trend_categories;
            }
        }
        private ObjectSet<trend_categories> _trend_categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<trend_tags> trend_tags
        {
            get
            {
                if ((_trend_tags == null))
                {
                    _trend_tags = base.CreateObjectSet<trend_tags>("trend_tags");
                }
                return _trend_tags;
            }
        }
        private ObjectSet<trend_tags> _trend_tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<users> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<users>("users");
                }
                return _users;
            }
        }
        private ObjectSet<users> _users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the alarm_categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToalarm_categories(alarm_categories alarm_categories)
        {
            base.AddObject("alarm_categories", alarm_categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the alarm_tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToalarm_tags(alarm_tags alarm_tags)
        {
            base.AddObject("alarm_tags", alarm_tags);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dig_tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodig_tags(dig_tags dig_tags)
        {
            base.AddObject("dig_tags", dig_tags);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the io_devices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToio_devices(io_devices io_devices)
        {
            base.AddObject("io_devices", io_devices);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologs(logs logs)
        {
            base.AddObject("logs", logs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the num_tag_types EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonum_tag_types(num_tag_types num_tag_types)
        {
            base.AddObject("num_tag_types", num_tag_types);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the num_tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonum_tags(num_tags num_tags)
        {
            base.AddObject("num_tags", num_tags);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosettings(settings settings)
        {
            base.AddObject("settings", settings);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the trend_categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotrend_categories(trend_categories trend_categories)
        {
            base.AddObject("trend_categories", trend_categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the trend_tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotrend_tags(trend_tags trend_tags)
        {
            base.AddObject("trend_tags", trend_tags);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(users users)
        {
            base.AddObject("users", users);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="alarm_categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class alarm_categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new alarm_categories object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static alarm_categories Createalarm_categories(global::System.Int32 id, global::System.String name)
        {
            alarm_categories alarm_categories = new alarm_categories();
            alarm_categories.id = id;
            alarm_categories.name = name;
            return alarm_categories;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> time_to_store
        {
            get
            {
                return _time_to_store;
            }
            set
            {
                Ontime_to_storeChanging(value);
                ReportPropertyChanging("time_to_store");
                _time_to_store = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time_to_store");
                Ontime_to_storeChanged();
            }
        }
        private Nullable<global::System.Int64> _time_to_store;
        partial void Ontime_to_storeChanging(Nullable<global::System.Int64> value);
        partial void Ontime_to_storeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_alarm_ta_reference_alarm_ca", "alarm_tags")]
        public EntityCollection<alarm_tags> alarm_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<alarm_tags>("PHmiModel.fk_alarm_ta_reference_alarm_ca", "alarm_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<alarm_tags>("PHmiModel.fk_alarm_ta_reference_alarm_ca", "alarm_tags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="alarm_tags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class alarm_tags : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new alarm_tags object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="ref_dig_tags">Initial value of the ref_dig_tags property.</param>
        /// <param name="ref_categories">Initial value of the ref_categories property.</param>
        /// <param name="acknowledgeable">Initial value of the acknowledgeable property.</param>
        public static alarm_tags Createalarm_tags(global::System.Int32 id, global::System.String name, global::System.Int32 ref_dig_tags, global::System.Int32 ref_categories, global::System.Boolean acknowledgeable)
        {
            alarm_tags alarm_tags = new alarm_tags();
            alarm_tags.id = id;
            alarm_tags.name = name;
            alarm_tags.ref_dig_tags = ref_dig_tags;
            alarm_tags.ref_categories = ref_categories;
            alarm_tags.acknowledgeable = acknowledgeable;
            return alarm_tags;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ref_dig_tags
        {
            get
            {
                return _ref_dig_tags;
            }
            set
            {
                Onref_dig_tagsChanging(value);
                ReportPropertyChanging("ref_dig_tags");
                _ref_dig_tags = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_dig_tags");
                Onref_dig_tagsChanged();
            }
        }
        private global::System.Int32 _ref_dig_tags;
        partial void Onref_dig_tagsChanging(global::System.Int32 value);
        partial void Onref_dig_tagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> privilege
        {
            get
            {
                return _privilege;
            }
            set
            {
                OnprivilegeChanging(value);
                ReportPropertyChanging("privilege");
                _privilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("privilege");
                OnprivilegeChanged();
            }
        }
        private Nullable<global::System.Int32> _privilege;
        partial void OnprivilegeChanging(Nullable<global::System.Int32> value);
        partial void OnprivilegeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ref_categories
        {
            get
            {
                return _ref_categories;
            }
            set
            {
                Onref_categoriesChanging(value);
                ReportPropertyChanging("ref_categories");
                _ref_categories = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_categories");
                Onref_categoriesChanged();
            }
        }
        private global::System.Int32 _ref_categories;
        partial void Onref_categoriesChanging(global::System.Int32 value);
        partial void Onref_categoriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean acknowledgeable
        {
            get
            {
                return _acknowledgeable;
            }
            set
            {
                OnacknowledgeableChanging(value);
                ReportPropertyChanging("acknowledgeable");
                _acknowledgeable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("acknowledgeable");
                OnacknowledgeableChanged();
            }
        }
        private global::System.Boolean _acknowledgeable;
        partial void OnacknowledgeableChanging(global::System.Boolean value);
        partial void OnacknowledgeableChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_alarm_ta_reference_alarm_ca", "alarm_categories")]
        public alarm_categories alarm_categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<alarm_categories>("PHmiModel.fk_alarm_ta_reference_alarm_ca", "alarm_categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<alarm_categories>("PHmiModel.fk_alarm_ta_reference_alarm_ca", "alarm_categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<alarm_categories> alarm_categoriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<alarm_categories>("PHmiModel.fk_alarm_ta_reference_alarm_ca", "alarm_categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<alarm_categories>("PHmiModel.fk_alarm_ta_reference_alarm_ca", "alarm_categories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_alarm_ta_reference_dig_tags", "dig_tags")]
        public dig_tags dig_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dig_tags>("PHmiModel.fk_alarm_ta_reference_dig_tags", "dig_tags").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dig_tags>("PHmiModel.fk_alarm_ta_reference_dig_tags", "dig_tags").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dig_tags> dig_tagsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dig_tags>("PHmiModel.fk_alarm_ta_reference_dig_tags", "dig_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dig_tags>("PHmiModel.fk_alarm_ta_reference_dig_tags", "dig_tags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="dig_tags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dig_tags : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dig_tags object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="ref_io_devices">Initial value of the ref_io_devices property.</param>
        /// <param name="device">Initial value of the device property.</param>
        /// <param name="can_read">Initial value of the can_read property.</param>
        public static dig_tags Createdig_tags(global::System.Int32 id, global::System.String name, global::System.Int32 ref_io_devices, global::System.String device, global::System.Boolean can_read)
        {
            dig_tags dig_tags = new dig_tags();
            dig_tags.id = id;
            dig_tags.name = name;
            dig_tags.ref_io_devices = ref_io_devices;
            dig_tags.device = device;
            dig_tags.can_read = can_read;
            return dig_tags;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ref_io_devices
        {
            get
            {
                return _ref_io_devices;
            }
            set
            {
                Onref_io_devicesChanging(value);
                ReportPropertyChanging("ref_io_devices");
                _ref_io_devices = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_io_devices");
                Onref_io_devicesChanged();
            }
        }
        private global::System.Int32 _ref_io_devices;
        partial void Onref_io_devicesChanging(global::System.Int32 value);
        partial void Onref_io_devicesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String device
        {
            get
            {
                return _device;
            }
            set
            {
                OndeviceChanging(value);
                ReportPropertyChanging("device");
                _device = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("device");
                OndeviceChanged();
            }
        }
        private global::System.String _device;
        partial void OndeviceChanging(global::System.String value);
        partial void OndeviceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean can_read
        {
            get
            {
                return _can_read;
            }
            set
            {
                Oncan_readChanging(value);
                ReportPropertyChanging("can_read");
                _can_read = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_read");
                Oncan_readChanged();
            }
        }
        private global::System.Boolean _can_read;
        partial void Oncan_readChanging(global::System.Boolean value);
        partial void Oncan_readChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_alarm_ta_reference_dig_tags", "alarm_tags")]
        public EntityCollection<alarm_tags> alarm_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<alarm_tags>("PHmiModel.fk_alarm_ta_reference_dig_tags", "alarm_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<alarm_tags>("PHmiModel.fk_alarm_ta_reference_dig_tags", "alarm_tags", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_dig_tags_reference_io_devic", "io_devices")]
        public io_devices io_devices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<io_devices>("PHmiModel.fk_dig_tags_reference_io_devic", "io_devices").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<io_devices>("PHmiModel.fk_dig_tags_reference_io_devic", "io_devices").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<io_devices> io_devicesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<io_devices>("PHmiModel.fk_dig_tags_reference_io_devic", "io_devices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<io_devices>("PHmiModel.fk_dig_tags_reference_io_devic", "io_devices", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_trend_ta_reference_dig_tags", "trend_tags")]
        public EntityCollection<trend_tags> trend_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<trend_tags>("PHmiModel.fk_trend_ta_reference_dig_tags", "trend_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<trend_tags>("PHmiModel.fk_trend_ta_reference_dig_tags", "trend_tags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="io_devices")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class io_devices : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new io_devices object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="type">Initial value of the type property.</param>
        public static io_devices Createio_devices(global::System.Int32 id, global::System.String name, global::System.String type)
        {
            io_devices io_devices = new io_devices();
            io_devices.id = id;
            io_devices.name = name;
            io_devices.type = type;
            return io_devices;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String options
        {
            get
            {
                return _options;
            }
            set
            {
                OnoptionsChanging(value);
                ReportPropertyChanging("options");
                _options = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("options");
                OnoptionsChanged();
            }
        }
        private global::System.String _options;
        partial void OnoptionsChanging(global::System.String value);
        partial void OnoptionsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_dig_tags_reference_io_devic", "dig_tags")]
        public EntityCollection<dig_tags> dig_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<dig_tags>("PHmiModel.fk_dig_tags_reference_io_devic", "dig_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<dig_tags>("PHmiModel.fk_dig_tags_reference_io_devic", "dig_tags", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_num_tags_reference_io_devic", "num_tags")]
        public EntityCollection<num_tags> num_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<num_tags>("PHmiModel.fk_num_tags_reference_io_devic", "num_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<num_tags>("PHmiModel.fk_num_tags_reference_io_devic", "num_tags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="logs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class logs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new logs object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static logs Createlogs(global::System.Int32 id, global::System.String name)
        {
            logs logs = new logs();
            logs.id = id;
            logs.name = name;
            return logs;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> time_to_store
        {
            get
            {
                return _time_to_store;
            }
            set
            {
                Ontime_to_storeChanging(value);
                ReportPropertyChanging("time_to_store");
                _time_to_store = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time_to_store");
                Ontime_to_storeChanged();
            }
        }
        private Nullable<global::System.Int64> _time_to_store;
        partial void Ontime_to_storeChanging(Nullable<global::System.Int64> value);
        partial void Ontime_to_storeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="num_tag_types")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class num_tag_types : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new num_tag_types object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static num_tag_types Createnum_tag_types(global::System.Int32 id, global::System.String name)
        {
            num_tag_types num_tag_types = new num_tag_types();
            num_tag_types.id = id;
            num_tag_types.name = name;
            return num_tag_types;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_num_tags_reference_num_tag_", "num_tags")]
        public EntityCollection<num_tags> num_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<num_tags>("PHmiModel.fk_num_tags_reference_num_tag_", "num_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<num_tags>("PHmiModel.fk_num_tags_reference_num_tag_", "num_tags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="num_tags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class num_tags : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new num_tags object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="ref_io_devices">Initial value of the ref_io_devices property.</param>
        /// <param name="ref_tag_types">Initial value of the ref_tag_types property.</param>
        /// <param name="device">Initial value of the device property.</param>
        /// <param name="can_read">Initial value of the can_read property.</param>
        public static num_tags Createnum_tags(global::System.Int32 id, global::System.String name, global::System.Int32 ref_io_devices, global::System.Int32 ref_tag_types, global::System.String device, global::System.Boolean can_read)
        {
            num_tags num_tags = new num_tags();
            num_tags.id = id;
            num_tags.name = name;
            num_tags.ref_io_devices = ref_io_devices;
            num_tags.ref_tag_types = ref_tag_types;
            num_tags.device = device;
            num_tags.can_read = can_read;
            return num_tags;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ref_io_devices
        {
            get
            {
                return _ref_io_devices;
            }
            set
            {
                Onref_io_devicesChanging(value);
                ReportPropertyChanging("ref_io_devices");
                _ref_io_devices = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_io_devices");
                Onref_io_devicesChanged();
            }
        }
        private global::System.Int32 _ref_io_devices;
        partial void Onref_io_devicesChanging(global::System.Int32 value);
        partial void Onref_io_devicesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ref_tag_types
        {
            get
            {
                return _ref_tag_types;
            }
            set
            {
                Onref_tag_typesChanging(value);
                ReportPropertyChanging("ref_tag_types");
                _ref_tag_types = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_tag_types");
                Onref_tag_typesChanged();
            }
        }
        private global::System.Int32 _ref_tag_types;
        partial void Onref_tag_typesChanging(global::System.Int32 value);
        partial void Onref_tag_typesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String device
        {
            get
            {
                return _device;
            }
            set
            {
                OndeviceChanging(value);
                ReportPropertyChanging("device");
                _device = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("device");
                OndeviceChanged();
            }
        }
        private global::System.String _device;
        partial void OndeviceChanging(global::System.String value);
        partial void OndeviceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean can_read
        {
            get
            {
                return _can_read;
            }
            set
            {
                Oncan_readChanging(value);
                ReportPropertyChanging("can_read");
                _can_read = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_read");
                Oncan_readChanged();
            }
        }
        private global::System.Boolean _can_read;
        partial void Oncan_readChanging(global::System.Boolean value);
        partial void Oncan_readChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eng_unit
        {
            get
            {
                return _eng_unit;
            }
            set
            {
                Oneng_unitChanging(value);
                ReportPropertyChanging("eng_unit");
                _eng_unit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eng_unit");
                Oneng_unitChanged();
            }
        }
        private global::System.String _eng_unit;
        partial void Oneng_unitChanging(global::System.String value);
        partial void Oneng_unitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> raw_min
        {
            get
            {
                return _raw_min;
            }
            set
            {
                Onraw_minChanging(value);
                ReportPropertyChanging("raw_min");
                _raw_min = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("raw_min");
                Onraw_minChanged();
            }
        }
        private Nullable<global::System.Double> _raw_min;
        partial void Onraw_minChanging(Nullable<global::System.Double> value);
        partial void Onraw_minChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> raw_max
        {
            get
            {
                return _raw_max;
            }
            set
            {
                Onraw_maxChanging(value);
                ReportPropertyChanging("raw_max");
                _raw_max = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("raw_max");
                Onraw_maxChanged();
            }
        }
        private Nullable<global::System.Double> _raw_max;
        partial void Onraw_maxChanging(Nullable<global::System.Double> value);
        partial void Onraw_maxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> eng_min
        {
            get
            {
                return _eng_min;
            }
            set
            {
                Oneng_minChanging(value);
                ReportPropertyChanging("eng_min");
                _eng_min = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eng_min");
                Oneng_minChanged();
            }
        }
        private Nullable<global::System.Double> _eng_min;
        partial void Oneng_minChanging(Nullable<global::System.Double> value);
        partial void Oneng_minChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> eng_max
        {
            get
            {
                return _eng_max;
            }
            set
            {
                Oneng_maxChanging(value);
                ReportPropertyChanging("eng_max");
                _eng_max = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eng_max");
                Oneng_maxChanged();
            }
        }
        private Nullable<global::System.Double> _eng_max;
        partial void Oneng_maxChanging(Nullable<global::System.Double> value);
        partial void Oneng_maxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String format
        {
            get
            {
                return _format;
            }
            set
            {
                OnformatChanging(value);
                ReportPropertyChanging("format");
                _format = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("format");
                OnformatChanged();
            }
        }
        private global::System.String _format;
        partial void OnformatChanging(global::System.String value);
        partial void OnformatChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_num_tags_reference_io_devic", "io_devices")]
        public io_devices io_devices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<io_devices>("PHmiModel.fk_num_tags_reference_io_devic", "io_devices").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<io_devices>("PHmiModel.fk_num_tags_reference_io_devic", "io_devices").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<io_devices> io_devicesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<io_devices>("PHmiModel.fk_num_tags_reference_io_devic", "io_devices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<io_devices>("PHmiModel.fk_num_tags_reference_io_devic", "io_devices", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_num_tags_reference_num_tag_", "num_tag_types")]
        public num_tag_types num_tag_types
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<num_tag_types>("PHmiModel.fk_num_tags_reference_num_tag_", "num_tag_types").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<num_tag_types>("PHmiModel.fk_num_tags_reference_num_tag_", "num_tag_types").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<num_tag_types> num_tag_typesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<num_tag_types>("PHmiModel.fk_num_tags_reference_num_tag_", "num_tag_types");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<num_tag_types>("PHmiModel.fk_num_tags_reference_num_tag_", "num_tag_types", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_trend_ta_reference_num_tags", "trend_tags")]
        public EntityCollection<trend_tags> trend_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<trend_tags>("PHmiModel.fk_trend_ta_reference_num_tags", "trend_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<trend_tags>("PHmiModel.fk_trend_ta_reference_num_tags", "trend_tags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="settings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class settings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new settings object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="guid">Initial value of the guid property.</param>
        /// <param name="guid2">Initial value of the guid2 property.</param>
        /// <param name="phmi_guid">Initial value of the phmi_guid property.</param>
        public static settings Createsettings(global::System.Int32 id, global::System.String guid, global::System.String guid2, global::System.String phmi_guid)
        {
            settings settings = new settings();
            settings.id = id;
            settings.guid = guid;
            settings.guid2 = guid2;
            settings.phmi_guid = phmi_guid;
            return settings;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String server
        {
            get
            {
                return _server;
            }
            set
            {
                OnserverChanging(value);
                ReportPropertyChanging("server");
                _server = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("server");
                OnserverChanged();
            }
        }
        private global::System.String _server;
        partial void OnserverChanging(global::System.String value);
        partial void OnserverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stand_by_server
        {
            get
            {
                return _stand_by_server;
            }
            set
            {
                Onstand_by_serverChanging(value);
                ReportPropertyChanging("stand_by_server");
                _stand_by_server = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stand_by_server");
                Onstand_by_serverChanged();
            }
        }
        private global::System.String _stand_by_server;
        partial void Onstand_by_serverChanging(global::System.String value);
        partial void Onstand_by_serverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String guid
        {
            get
            {
                return _guid;
            }
            set
            {
                OnguidChanging(value);
                ReportPropertyChanging("guid");
                _guid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("guid");
                OnguidChanged();
            }
        }
        private global::System.String _guid;
        partial void OnguidChanging(global::System.String value);
        partial void OnguidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String guid2
        {
            get
            {
                return _guid2;
            }
            set
            {
                Onguid2Changing(value);
                ReportPropertyChanging("guid2");
                _guid2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("guid2");
                Onguid2Changed();
            }
        }
        private global::System.String _guid2;
        partial void Onguid2Changing(global::System.String value);
        partial void Onguid2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phmi_guid
        {
            get
            {
                return _phmi_guid;
            }
            set
            {
                Onphmi_guidChanging(value);
                ReportPropertyChanging("phmi_guid");
                _phmi_guid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phmi_guid");
                Onphmi_guidChanged();
            }
        }
        private global::System.String _phmi_guid;
        partial void Onphmi_guidChanging(global::System.String value);
        partial void Onphmi_guidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="trend_categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class trend_categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new trend_categories object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="period">Initial value of the period property.</param>
        public static trend_categories Createtrend_categories(global::System.Int32 id, global::System.String name, global::System.Int64 period)
        {
            trend_categories trend_categories = new trend_categories();
            trend_categories.id = id;
            trend_categories.name = name;
            trend_categories.period = period;
            return trend_categories;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> time_to_store
        {
            get
            {
                return _time_to_store;
            }
            set
            {
                Ontime_to_storeChanging(value);
                ReportPropertyChanging("time_to_store");
                _time_to_store = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time_to_store");
                Ontime_to_storeChanged();
            }
        }
        private Nullable<global::System.Int64> _time_to_store;
        partial void Ontime_to_storeChanging(Nullable<global::System.Int64> value);
        partial void Ontime_to_storeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 period
        {
            get
            {
                return _period;
            }
            set
            {
                OnperiodChanging(value);
                ReportPropertyChanging("period");
                _period = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("period");
                OnperiodChanged();
            }
        }
        private global::System.Int64 _period;
        partial void OnperiodChanging(global::System.Int64 value);
        partial void OnperiodChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_trend_ta_reference_trend_ca", "trend_tags")]
        public EntityCollection<trend_tags> trend_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<trend_tags>("PHmiModel.fk_trend_ta_reference_trend_ca", "trend_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<trend_tags>("PHmiModel.fk_trend_ta_reference_trend_ca", "trend_tags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="trend_tags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class trend_tags : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new trend_tags object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="ref_num_tags">Initial value of the ref_num_tags property.</param>
        /// <param name="ref_categories">Initial value of the ref_categories property.</param>
        public static trend_tags Createtrend_tags(global::System.Int32 id, global::System.String name, global::System.Int32 ref_num_tags, global::System.Int32 ref_categories)
        {
            trend_tags trend_tags = new trend_tags();
            trend_tags.id = id;
            trend_tags.name = name;
            trend_tags.ref_num_tags = ref_num_tags;
            trend_tags.ref_categories = ref_categories;
            return trend_tags;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ref_num_tags
        {
            get
            {
                return _ref_num_tags;
            }
            set
            {
                Onref_num_tagsChanging(value);
                ReportPropertyChanging("ref_num_tags");
                _ref_num_tags = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_num_tags");
                Onref_num_tagsChanged();
            }
        }
        private global::System.Int32 _ref_num_tags;
        partial void Onref_num_tagsChanging(global::System.Int32 value);
        partial void Onref_num_tagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ref_categories
        {
            get
            {
                return _ref_categories;
            }
            set
            {
                Onref_categoriesChanging(value);
                ReportPropertyChanging("ref_categories");
                _ref_categories = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_categories");
                Onref_categoriesChanged();
            }
        }
        private global::System.Int32 _ref_categories;
        partial void Onref_categoriesChanging(global::System.Int32 value);
        partial void Onref_categoriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ref_triggers
        {
            get
            {
                return _ref_triggers;
            }
            set
            {
                Onref_triggersChanging(value);
                ReportPropertyChanging("ref_triggers");
                _ref_triggers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_triggers");
                Onref_triggersChanged();
            }
        }
        private Nullable<global::System.Int32> _ref_triggers;
        partial void Onref_triggersChanging(Nullable<global::System.Int32> value);
        partial void Onref_triggersChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_trend_ta_reference_dig_tags", "dig_tags")]
        public dig_tags dig_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dig_tags>("PHmiModel.fk_trend_ta_reference_dig_tags", "dig_tags").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dig_tags>("PHmiModel.fk_trend_ta_reference_dig_tags", "dig_tags").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dig_tags> dig_tagsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dig_tags>("PHmiModel.fk_trend_ta_reference_dig_tags", "dig_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dig_tags>("PHmiModel.fk_trend_ta_reference_dig_tags", "dig_tags", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_trend_ta_reference_num_tags", "num_tags")]
        public num_tags num_tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<num_tags>("PHmiModel.fk_trend_ta_reference_num_tags", "num_tags").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<num_tags>("PHmiModel.fk_trend_ta_reference_num_tags", "num_tags").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<num_tags> num_tagsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<num_tags>("PHmiModel.fk_trend_ta_reference_num_tags", "num_tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<num_tags>("PHmiModel.fk_trend_ta_reference_num_tags", "num_tags", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PHmiModel", "fk_trend_ta_reference_trend_ca", "trend_categories")]
        public trend_categories trend_categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<trend_categories>("PHmiModel.fk_trend_ta_reference_trend_ca", "trend_categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<trend_categories>("PHmiModel.fk_trend_ta_reference_trend_ca", "trend_categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<trend_categories> trend_categoriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<trend_categories>("PHmiModel.fk_trend_ta_reference_trend_ca", "trend_categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<trend_categories>("PHmiModel.fk_trend_ta_reference_trend_ca", "trend_categories", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHmiModel", Name="users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new users object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="enabled">Initial value of the enabled property.</param>
        /// <param name="can_change">Initial value of the can_change property.</param>
        public static users Createusers(global::System.Int32 id, global::System.String name, global::System.String description, global::System.Boolean enabled, global::System.Boolean can_change)
        {
            users users = new users();
            users.id = id;
            users.name = name;
            users.description = description;
            users.enabled = enabled;
            users.can_change = can_change;
            return users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] photo
        {
            get
            {
                return StructuralObject.GetValidValue(_photo);
            }
            set
            {
                OnphotoChanging(value);
                ReportPropertyChanging("photo");
                _photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo");
                OnphotoChanged();
            }
        }
        private global::System.Byte[] _photo;
        partial void OnphotoChanging(global::System.Byte[] value);
        partial void OnphotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean enabled
        {
            get
            {
                return _enabled;
            }
            set
            {
                OnenabledChanging(value);
                ReportPropertyChanging("enabled");
                _enabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("enabled");
                OnenabledChanged();
            }
        }
        private global::System.Boolean _enabled;
        partial void OnenabledChanging(global::System.Boolean value);
        partial void OnenabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean can_change
        {
            get
            {
                return _can_change;
            }
            set
            {
                Oncan_changeChanging(value);
                ReportPropertyChanging("can_change");
                _can_change = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_change");
                Oncan_changeChanged();
            }
        }
        private global::System.Boolean _can_change;
        partial void Oncan_changeChanging(global::System.Boolean value);
        partial void Oncan_changeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> privilege
        {
            get
            {
                return _privilege;
            }
            set
            {
                OnprivilegeChanging(value);
                ReportPropertyChanging("privilege");
                _privilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("privilege");
                OnprivilegeChanged();
            }
        }
        private Nullable<global::System.Int32> _privilege;
        partial void OnprivilegeChanging(Nullable<global::System.Int32> value);
        partial void OnprivilegeChanged();

        #endregion

    
    }

    #endregion

    
}
