//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHmiResources.Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PHmiResources.Loc.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgeable.
        /// </summary>
        public static string Acknowledgeable {
            get {
                return ResourceManager.GetString("Acknowledgeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add alarm category.
        /// </summary>
        public static string AddAlarmCategory {
            get {
                return ResourceManager.GetString("AddAlarmCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add alarm tag.
        /// </summary>
        public static string AddAlarmTag {
            get {
                return ResourceManager.GetString("AddAlarmTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add digital tag.
        /// </summary>
        public static string AddDigitalTag {
            get {
                return ResourceManager.GetString("AddDigitalTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add I/O device.
        /// </summary>
        public static string AddIoDevice {
            get {
                return ResourceManager.GetString("AddIoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add log.
        /// </summary>
        public static string AddLog {
            get {
                return ResourceManager.GetString("AddLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add numeric tag.
        /// </summary>
        public static string AddNumericTag {
            get {
                return ResourceManager.GetString("AddNumericTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address in device.
        /// </summary>
        public static string AddressInDevice {
            get {
                return ResourceManager.GetString("AddressInDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add (Ctrl+N).
        /// </summary>
        public static string AddToolTip {
            get {
                return ResourceManager.GetString("AddToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add trend category.
        /// </summary>
        public static string AddTrendCategory {
            get {
                return ResourceManager.GetString("AddTrendCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add trend tag.
        /// </summary>
        public static string AddTrendTag {
            get {
                return ResourceManager.GetString("AddTrendTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm categories.
        /// </summary>
        public static string AlarmCategories {
            get {
                return ResourceManager.GetString("AlarmCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm category.
        /// </summary>
        public static string AlarmCategory {
            get {
                return ResourceManager.GetString("AlarmCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        public static string Alarms {
            get {
                return ResourceManager.GetString("Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms &quot;{0}&quot; started.
        /// </summary>
        public static string AlarmsStartedMessage {
            get {
                return ResourceManager.GetString("AlarmsStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms &quot;{0}&quot; stopped.
        /// </summary>
        public static string AlarmsStoppedMessage {
            get {
                return ResourceManager.GetString("AlarmsStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm tags.
        /// </summary>
        public static string AlarmTags {
            get {
                return ResourceManager.GetString("AlarmTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &quot;{0}&quot; does not contain type &quot;{1}&quot;.
        /// </summary>
        public static string AssemblyDoesNotContainInterfaceImplementantionMessage {
            get {
                return ResourceManager.GetString("AssemblyDoesNotContainInterfaceImplementantionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup files.
        /// </summary>
        public static string BackupFiles {
            get {
                return ResourceManager.GetString("BackupFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build client.
        /// </summary>
        public static string BuildClient {
            get {
                return ResourceManager.GetString("BuildClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build complete.
        /// </summary>
        public static string BuildComplete {
            get {
                return ResourceManager.GetString("BuildComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry editable.
        /// </summary>
        public static string CanChange {
            get {
                return ResourceManager.GetString("CanChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can read.
        /// </summary>
        public static string CanRead {
            get {
                return ResourceManager.GetString("CanRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change selector when module has uncommited changes..
        /// </summary>
        public static string CantChangeSelectorMessage {
            get {
                return ResourceManager.GetString("CantChangeSelectorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (Ctrl+Q).
        /// </summary>
        public static string CloseModuleToolTip {
            get {
                return ResourceManager.GetString("CloseModuleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns count does not match.
        /// </summary>
        public static string ColumnsCountNotMatchMessage {
            get {
                return ResourceManager.GetString("ColumnsCountNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; cannot include symbol &quot;;&quot;.
        /// </summary>
        public static string ConnectionParameterErrorMessage {
            get {
                return ResourceManager.GetString("ConnectionParameterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string ContinueQuestion {
            get {
                return ResourceManager.GetString("ContinueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        public static string CopyToolTip {
            get {
                return ResourceManager.GetString("CopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &quot;{0}&quot; created.
        /// </summary>
        public static string DatabaseCreatedMessage {
            get {
                return ResourceManager.GetString("DatabaseCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected rows?.
        /// </summary>
        public static string DeleteRowsQuestion {
            get {
                return ResourceManager.GetString("DeleteRowsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (Ctrl+D).
        /// </summary>
        public static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital tag.
        /// </summary>
        public static string DigitalTag {
            get {
                return ResourceManager.GetString("DigitalTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital tag with the same field &quot;{0}&quot; is present for items:.
        /// </summary>
        public static string DigitalTagPresentMessage {
            get {
                return ResourceManager.GetString("DigitalTagPresentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital tags.
        /// </summary>
        public static string DigitalTags {
            get {
                return ResourceManager.GetString("DigitalTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; should be a valid .NET variable name.
        /// </summary>
        public static string DotNetNameMessage {
            get {
                return ResourceManager.GetString("DotNetNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; should be a valid .NET namespace name.
        /// </summary>
        public static string DotNetNameSpaceMessage {
            get {
                return ResourceManager.GetString("DotNetNameSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alarm category.
        /// </summary>
        public static string EditAlarmCategory {
            get {
                return ResourceManager.GetString("EditAlarmCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alarm tag.
        /// </summary>
        public static string EditAlarmTag {
            get {
                return ResourceManager.GetString("EditAlarmTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit digital tag.
        /// </summary>
        public static string EditDigitalTag {
            get {
                return ResourceManager.GetString("EditDigitalTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit I/O device.
        /// </summary>
        public static string EditIoDevice {
            get {
                return ResourceManager.GetString("EditIoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit log.
        /// </summary>
        public static string EditLog {
            get {
                return ResourceManager.GetString("EditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit numeric tag.
        /// </summary>
        public static string EditNumericTag {
            get {
                return ResourceManager.GetString("EditNumericTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit (Ctrl+E).
        /// </summary>
        public static string EditToolTip {
            get {
                return ResourceManager.GetString("EditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit trend category.
        /// </summary>
        public static string EditTrendCategory {
            get {
                return ResourceManager.GetString("EditTrendCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit trend tag.
        /// </summary>
        public static string EditTrendTag {
            get {
                return ResourceManager.GetString("EditTrendTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng max.
        /// </summary>
        public static string EngMax {
            get {
                return ResourceManager.GetString("EngMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng min.
        /// </summary>
        public static string EngMin {
            get {
                return ResourceManager.GetString("EngMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer unit.
        /// </summary>
        public static string EngUnit {
            get {
                return ResourceManager.GetString("EngUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed.
        /// </summary>
        public static string ExportCompleted {
            get {
                return ResourceManager.GetString("ExportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; is not assembly.
        /// </summary>
        public static string FileNotAssemblyMessage {
            get {
                return ResourceManager.GetString("FileNotAssemblyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; is not found.
        /// </summary>
        public static string FileNotFoundMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module has uncommited changes..
        /// </summary>
        public static string HasChangesMessage {
            get {
                return ResourceManager.GetString("HasChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide at start.
        /// </summary>
        public static string HideAtStart {
            get {
                return ResourceManager.GetString("HideAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import сompleted.
        /// </summary>
        public static string ImportCompleted {
            get {
                return ResourceManager.GetString("ImportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install service.
        /// </summary>
        public static string InstallService {
            get {
                return ResourceManager.GetString("InstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; should contain a valid double value.
        /// </summary>
        public static string InvalidDoubleMessage {
            get {
                return ResourceManager.GetString("InvalidDoubleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; should contain a valid time span value. Example: &quot;{1}&quot;.
        /// </summary>
        public static string InvalidTimeSpanMessage {
            get {
                return ResourceManager.GetString("InvalidTimeSpanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O device.
        /// </summary>
        public static string IoDevice {
            get {
                return ResourceManager.GetString("IoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O devices.
        /// </summary>
        public static string IoDevices {
            get {
                return ResourceManager.GetString("IoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O device &quot;{0}&quot; started.
        /// </summary>
        public static string IoDeviceStartedMessage {
            get {
                return ResourceManager.GetString("IoDeviceStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O device &quot;{0}&quot; stopped.
        /// </summary>
        public static string IoDeviceStoppedMessage {
            get {
                return ResourceManager.GetString("IoDeviceStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O device &quot;{0}&quot;.
        /// </summary>
        public static string IoDeviceWithName {
            get {
                return ResourceManager.GetString("IoDeviceWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with specified id &quot;{0}&quot; was not found.
        /// </summary>
        public static string ItemWithIdNotFoundMessage {
            get {
                return ResourceManager.GetString("ItemWithIdNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; length can&apos;t be more than {1}.
        /// </summary>
        public static string LengthMessage {
            get {
                return ResourceManager.GetString("LengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log &quot;{0}&quot; started.
        /// </summary>
        public static string LogStargedMessage {
            get {
                return ResourceManager.GetString("LogStargedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log &quot;{0}&quot; stopped.
        /// </summary>
        public static string LogStoppedMessage {
            get {
                return ResourceManager.GetString("LogStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string NameSpace {
            get {
                return ResourceManager.GetString("NameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &quot;{0}&quot; is not PHmi project database.
        /// </summary>
        public static string NotPHmiDatabaseMessage {
            get {
                return ResourceManager.GetString("NotPHmiDatabaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not valid id.
        /// </summary>
        public static string NotValidIdMessage {
            get {
                return ResourceManager.GetString("NotValidIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric tag.
        /// </summary>
        public static string NumericTag {
            get {
                return ResourceManager.GetString("NumericTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric tag with the same field &quot;{0}&quot; is present for items:.
        /// </summary>
        public static string NumericTagPresentMessage {
            get {
                return ResourceManager.GetString("NumericTagPresentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric tags.
        /// </summary>
        public static string NumericTags {
            get {
                return ResourceManager.GetString("NumericTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when inserting row where &quot;{0}&quot;=&quot;{1}&quot; and &quot;{2}&quot;=&quot;{3}&quot;: {4}.
        /// </summary>
        public static string PasteRowErrorMessage {
            get {
                return ResourceManager.GetString("PasteRowErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        public static string PasteToolTip {
            get {
                return ResourceManager.GetString("PasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue.
        /// </summary>
        public static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege.
        /// </summary>
        public static string Privilege {
            get {
                return ResourceManager.GetString("Privilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &quot;{0}&quot; started.
        /// </summary>
        public static string ProjectStartedMessage {
            get {
                return ResourceManager.GetString("ProjectStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &quot;{0}&quot; is starting.
        /// </summary>
        public static string ProjectStartingMessage {
            get {
                return ResourceManager.GetString("ProjectStartingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &quot;{0}&quot; stopped.
        /// </summary>
        public static string ProjectStoppedMessage {
            get {
                return ResourceManager.GetString("ProjectStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &quot;{0}&quot; is stopping.
        /// </summary>
        public static string ProjectStoppingMessage {
            get {
                return ResourceManager.GetString("ProjectStoppingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick start guide.
        /// </summary>
        public static string QuickStartGuide {
            get {
                return ResourceManager.GetString("QuickStartGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw max.
        /// </summary>
        public static string RawMax {
            get {
                return ResourceManager.GetString("RawMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw min.
        /// </summary>
        public static string RawMin {
            get {
                return ResourceManager.GetString("RawMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload (Ctrl+R).
        /// </summary>
        public static string ReloadToolTip {
            get {
                return ResourceManager.GetString("ReloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; is required.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row is in editing mode.
        /// </summary>
        public static string RowInEditingMode {
            get {
                return ResourceManager.GetString("RowInEditingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows stored.
        /// </summary>
        public static string RowsStored {
            get {
                return ResourceManager.GetString("RowsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Ctrl+S).
        /// </summary>
        public static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows selected: {0:N0}.
        /// </summary>
        public static string SelectedRowsStatus {
            get {
                return ResourceManager.GetString("SelectedRowsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; must be in format &quot;Server:Port&quot;.
        /// </summary>
        public static string ServerNameMessage {
            get {
                return ResourceManager.GetString("ServerNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is started.
        /// </summary>
        public static string ServiceIsStarted {
            get {
                return ResourceManager.GetString("ServiceIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is stopped.
        /// </summary>
        public static string ServiceIsStopped {
            get {
                return ResourceManager.GetString("ServiceIsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand by server.
        /// </summary>
        public static string StandByServer {
            get {
                return ResourceManager.GetString("StandByServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start error.
        /// </summary>
        public static string StartError {
            get {
                return ResourceManager.GetString("StartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop error.
        /// </summary>
        public static string StopError {
            get {
                return ResourceManager.GetString("StopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string TablesStored {
            get {
                return ResourceManager.GetString("TablesStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag type.
        /// </summary>
        public static string TagType {
            get {
                return ResourceManager.GetString("TagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are uncommited changes..
        /// </summary>
        public static string ThereAreChangesMessage {
            get {
                return ResourceManager.GetString("ThereAreChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to store.
        /// </summary>
        public static string TimeToStore {
            get {
                return ResourceManager.GetString("TimeToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many trend tags in a category (max is {0}).
        /// </summary>
        public static string TooManyTrendTagsInCategoryMessage {
            get {
                return ResourceManager.GetString("TooManyTrendTagsInCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows total: {0:N0}.
        /// </summary>
        public static string TotalRowsStatus {
            get {
                return ResourceManager.GetString("TotalRowsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend categories.
        /// </summary>
        public static string TrendCategories {
            get {
                return ResourceManager.GetString("TrendCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend category.
        /// </summary>
        public static string TrendCategory {
            get {
                return ResourceManager.GetString("TrendCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string Trends {
            get {
                return ResourceManager.GetString("Trends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends &quot;{0}&quot; started.
        /// </summary>
        public static string TrendsStartedMessage {
            get {
                return ResourceManager.GetString("TrendsStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends &quot;{0}&quot; stopped.
        /// </summary>
        public static string TrendsStoppedMessage {
            get {
                return ResourceManager.GetString("TrendsStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend tag.
        /// </summary>
        public static string TrendTag {
            get {
                return ResourceManager.GetString("TrendTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend tags.
        /// </summary>
        public static string TrendTags {
            get {
                return ResourceManager.GetString("TrendTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        public static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger I/O device.
        /// </summary>
        public static string TriggerIoDevice {
            get {
                return ResourceManager.GetString("TriggerIoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; does not have a valid constructor.
        /// </summary>
        public static string TypeDoesNotHaveConstructorMessage {
            get {
                return ResourceManager.GetString("TypeDoesNotHaveConstructorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; not supported.
        /// </summary>
        public static string TypeNotSupportedMessage {
            get {
                return ResourceManager.GetString("TypeNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall service.
        /// </summary>
        public static string UninstallService {
            get {
                return ResourceManager.GetString("UninstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; must be unique. Dublicate items are:.
        /// </summary>
        public static string UniqueErrorMessage {
            get {
                return ResourceManager.GetString("UniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect.
        /// </summary>
        public static string Unselect {
            get {
                return ResourceManager.GetString("Unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect (Ctrl+U).
        /// </summary>
        public static string UnselectToolTip {
            get {
                return ResourceManager.GetString("UnselectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom connection string.
        /// </summary>
        public static string UseCustomConnectionString {
            get {
                return ResourceManager.GetString("UseCustomConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use project connection string.
        /// </summary>
        public static string UseProjectConnectionString {
            get {
                return ResourceManager.GetString("UseProjectConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User enabled.
        /// </summary>
        public static string UserEnabled {
            get {
                return ResourceManager.GetString("UserEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users service started.
        /// </summary>
        public static string UsersServiceStarted {
            get {
                return ResourceManager.GetString("UsersServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields are not set or invalid data is entered.
        /// </summary>
        public static string ValidationErrorMessage {
            get {
                return ResourceManager.GetString("ValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
